---
version: 0.2

env:
  variables:
    POSTGRESQL_VERSION: 11.7
    PSYCOPG2_VERSION: 2.8.4

phases:
  install:
    command:
      - yum update
      - yum install 

  pre_build:
    commands:
      - bash -ex download.sh

  build:
    commands:
      - bash -ex build_postgres.sh
      #- bash -ex build_psycopg2.sh
