---
version: 0.2

env:
  variables:
    POSTGRESQL_VERSION: 11.7
    PSYCOPG2_VERSION: 2.8.4

phases:
  install:
    runtime_versions:
      python: 3.7
    command:
      - yum update
      - yum install 

  pre_build:
    commands:
      - pip install --upgrade pip setuptools wheel
      - bash -x download.sh

  build:
    commands:
      - bash -ex build_postgres.sh
      - bash -ex build_psycopg2.sh
      - ls psycopg2-*/dist/*.whl

artifacts:
  wheel:
    files:
      - psycopg2-2.8.4/dist/psycopg2-2.8.4-cp37-cp37-linux_x86_64.whl
    discard-paths: yes
    name: psycopg2-$(date +%s)
